// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfnbmoujvgiybmfuzsen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmbmJtb3VqdmdpeWJtZnV6c2VuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNzEyNzUsImV4cCI6MjA3Mzc0NzI3NX0.Jn6ALp2I4mxxnpnVVM5CtRcaxbB6Rj9M2uFjB6faV8A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});